name: Build and deploy

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  env:
    runs-on: ubuntu-latest
    steps:
      - name: Get environment from git ref
        id: environment
        run: |
          echo "Running on branch ${{ github.ref_name }}"
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "environment=production"
            echo "environment=production" >> $GITHUB_OUTPUT
            echo "environment_short=prod" >> $GITHUB_OUTPUT
          else
            echo "environment=review/${{ github.ref_name }}"
            echo "environment=review/${{ github.ref_name }}" >> $GITHUB_OUTPUT
            echo "environment_short=$(echo -n ${{ github.ref_name }} | sed 's/feature[_/]//' | tr '_' '-' | tr '[:upper:]' '[:lower:]' | cut -c1-24 | sed 's/-*$//' )" >> $GITHUB_OUTPUT
          fi
    outputs:
      environment: "${{ steps.environment.outputs.environment }}"
      environment_short: "${{ steps.environment.outputs.environment_short }}"
      registry: ghcr.io
      image: ${{ github.repository }}/${{ github.ref_name }}

  vars:
    needs: [env]
    runs-on: ubuntu-latest
    environment:
      name: ${{ needs.env.outputs.environment }}
    steps:
      - name: Generate public URL
        id: public_url
        run: |
          if [[ -z "${{ vars.PUBLIC_URL }}" ]]; then
            public_url=https://${{ needs.env.outputs.environment_short }}.${{ vars.KUBE_INGRESS_BASE_DOMAIN }}
          else
            public_url="${{ vars.PUBLIC_URL }}"
          fi
          echo "public_url=$public_url" >> $GITHUB_OUTPUT
    outputs:
      PUBLIC_URL: ${{ steps.public_url.outputs.public_url }}

  build:
    needs: [env, vars]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ needs.env.outputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ needs.env.outputs.registry }}/${{ needs.env.outputs.image }}
          tags: |
            type=raw,value={{sha}}
            type=ref,event=branch

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            NUXT_PUBLIC_API_BASE_URL="${{ vars.NUXT_PUBLIC_API_BASE_URL }}"
            NEXT_PUBLIC_APP_BASE_URL="${{ needs.vars.outputs.PUBLIC_URL }}"
            NUXT_PUBLIC_MAP_TILE_LAYER_URL="${{ vars.NUXT_PUBLIC_MAP_TILE_LAYER_URL }}"
            NUXT_PUBLIC_MAP_TILE_LAYER_ATTRIBUTION="${{ vars.NUXT_PUBLIC_MAP_TILE_LAYER_ATTRIBUTION }}"
            NEXT_PUBLIC_MATOMO_BASE_URL="${{ vars.NEXT_PUBLIC_MATOMO_BASE_URL }}"
            NEXT_PUBLIC_MATOMO_ID="${{ vars.NEXT_PUBLIC_MATOMO_ID }}"
            NEXT_PUBLIC_REDMINE_ID="${{ vars.SERVICE_ID }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: [env, vars, build]
    uses: acdh-oeaw/gl-autodevops-minimal-port/.github/workflows/deploy.yml@main
    secrets: inherit
    with:
      environment: ${{ needs.env.outputs.environment }}
      DOCKER_TAG: ${{ needs.env.outputs.registry }}/${{ needs.env.outputs.image }}
      APP_NAME: "nuxt-vicav-${{ needs.env.outputs.environment_short }}"
      APP_ROOT: "/"
      SERVICE_ID: ${{ vars.SERVICE_ID }}
      PUBLIC_URL: ${{ needs.vars.outputs.PUBLIC_URL }}
      default_port: "3000"
