name: RenderApi

jobs:
  Linux:
    name: Test and Render API docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1
      - uses: kong/setup-inso@v1
        with:
          inso-version: 2.4.0
      - name: Run test suites
        run: inso run test -w /vicav-app-api spc_8ea7cf -e env_env_9a21f4d181d64765d33c7bbe158a0e24fc2976d0 --verbose
      - name: Generate yaml
        run: inso export spec -w /vicav-app-api spc_8ea7cf > assets/output.yaml
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply php-cs-fixer changes

